[package]
name = "credentialsd-common"
version = "0.1.0"
edition = "2024"
authors = ["Isaiah Inuwa <isaiah.inuwa@gmail.com>", "Martin Sirringhaus <martin.sirringhaus@suse.com>", "Alfie Fresta <alfie.fresta@gmail.com>"]
license = "LGPL-3.0-only"

[dependencies]
futures-lite = "2.6.0"
# libwebauthn = "0.2"
libwebauthn = { path = "../../libwebauthn/libwebauthn", features = ["libnfc"] }
serde = { version = "1", features = ["derive"] }
zvariant = "5.6.0"
