name: Build project
on:
  push:
    branches:
      - main
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_HOME: build/cargo-home
jobs:
  build:
    env:
      RUST_LOG: debug
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Update apt cache
        run: sudo apt update
      - name: Install system dependencies
        run: |
          sudo apt install -y --no-install-recommends \
            curl git build-essential \
            libgtk-4-dev libclang-dev libdbus-1-dev libssl-dev libudev-dev libnfc-dev \
            libpcsclite-dev libxml2-utils \
            blueprint-compiler desktop-file-utils gettext ninja-build python3-pip \
            udev zip
      - name: Install Meson
        run: |
          # Newer version needed for --interactive flag needed below
          python3 -m pip install --user -v 'meson==1.5.0'
      - name: Setup meson project
        run: meson setup build
      - name: Build
        run: ninja -C build
      - name: Test
        # We have to use the --interactive flag because of some
        # weird issue with meson hanging after cargo exits due to the TestDBus.
        # Probably has to do with forking the test processes.
        run: meson test --interactive
        working-directory: build/
      - name: Check clippy recommendations
        run: cargo clippy --workspace --all-features --target-dir build/target
      - name: Check formatting
        run: cargo fmt --all --check
